// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/jfussion/ignite-attendance-cloud-functions/domain"
	mock "github.com/stretchr/testify/mock"
)

// PeopleUsecase is an autogenerated mock type for the PeopleUsecase type
type PeopleUsecase struct {
	mock.Mock
}

// Get provides a mock function with given fields: ctx, id
func (_m *PeopleUsecase) Get(ctx context.Context, id string) (domain.People, error) {
	ret := _m.Called(ctx, id)

	var r0 domain.People
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.People); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.People)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
