// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	firestore "cloud.google.com/go/firestore"
	mock "github.com/stretchr/testify/mock"
)

// Doc is an autogenerated mock type for the Doc type
type Doc struct {
	mock.Mock
}

// Doc provides a mock function with given fields: path
func (_m *Doc) Doc(path string) *firestore.DocumentRef {
	ret := _m.Called(path)

	var r0 *firestore.DocumentRef
	if rf, ok := ret.Get(0).(func(string) *firestore.DocumentRef); ok {
		r0 = rf(path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*firestore.DocumentRef)
		}
	}

	return r0
}
